#!/usr/bin/env python3
"""Generate the Doxygen "Device bindings" reference from the driver bindings.

Reads every src/drivers/**/<compatible>.yaml binding and every board
description (with the overlays in its directory), and writes one Doxygen page
with a section per compatible: its driver, sources, capabilities, properties,
and the boards that enable it. Run by scripts/build_docs.sh, so the reference
always matches the bindings in the tree.
"""
import argparse
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import devicetree_generate as dt  # noqa: E402  (shares the description loader)

# Binding flags and what the driver then provides.
CAPABILITIES = {
    "console": "Can be `chosen.console`: exports `<driver>_console_ops`",
    "isr": "Handles its interrupt: `<driver>_isr()` is called by `dt_irq_dispatch()`",
    "gpio": "GPIO port: exports `<driver>_gpio_ops`; `gpio` properties can name it",
    "led": "LED: exports `<driver>_led_ops`; numbered in `dt_led_table`",
    "block": "Block device: exports `<driver>_block_ops`; `mounts` can name it",
}
# Hand-written driver pages, by binding directory.
DRIVER_PAGES = {
    "serial": "driver_serial",
    "gpio": "driver_gpio",
    "led": "driver_led",
    "block": "driver_block",
}


def slug(compatible):
    return "binding_" + re.sub(r"[^a-z0-9]+", "_", compatible.lower())


def cell(text):
    """Make text safe inside a Markdown table cell."""
    return str(text).replace("|", "\\|").replace("\n", " ")


def constraints(spec):
    parts = []
    if "minimum" in spec:
        parts.append(f"at least {spec['minimum']}")
    if "maximum" in spec:
        parts.append(f"at most {spec['maximum']}")
    if "multiple" in spec:
        parts.append(f"multiple of {spec['multiple']}")
    if spec.get("unique") and "unique-with" in spec:
        parts.append(f"unique per `{spec['unique-with']}`")
    elif spec.get("unique"):
        parts.append("unique")
    if spec.get("type") == "devpath":
        parts.append("unique `/dev` name")
    if "buffer" in spec:
        parts.append(f"allocates a `.bss` buffer (field `{spec['buffer']}`)")
    return ", ".join(parts) or "—"


def default(spec):
    if spec.get("type") == "devpath":
        return "the node name"
    if "default" in spec:
        value = spec["default"]
        return f"`{str(value).lower() if isinstance(value, bool) else value}`"
    return "—"


def board_configurations(board_root):
    """Yield (label, board path, overlay paths) for every board and overlay."""
    for board in sorted(Path(board_root).glob("*/board.yaml")):
        yield board.parent.name, board, []
        for overlay in sorted(board.parent.glob("*.yaml")):
            if overlay.name != "board.yaml":
                yield f"{board.parent.name} + {overlay.name}", board, [overlay]


def usage(board_root, soc_root, arch_root):
    """Map each compatible to [(configuration, [enabled node names])]."""
    used = {}
    for label, board_path, overlays in board_configurations(board_root):
        board, _, _, soc, _ = dt.select(board_path, soc_root, arch_root)
        description = dt.merge(soc, board, "board")
        for overlay in overlays:
            description = dt.merge(description, dt.load(overlay), overlay.name)
        nodes = {}
        for name, node in description.get("devices", {}).items():
            if node.get("status", "okay") == "okay":
                nodes.setdefault(node.get("compatible"), []).append(name)
        for compatible, names in nodes.items():
            used.setdefault(compatible, []).append((label, names))
    return used


def render(bindings, used, root):
    lines = [
        "/**",
        "@page bindings Device bindings",
        "@brief Every compatible a device description can use, generated from the bindings.",
        "",
        "@tableofcontents",
        "",
        "Generated by `scripts/bindings_doc.py` from `src/drivers/<class>/<compatible>.yaml` "
        "and the board descriptions when the documentation is built. How bindings, "
        "properties, and capabilities work is described in @ref drivers_guide.",
        "",
        "| Compatible | Driver | Summary |",
        "| --- | --- | --- |",
    ]
    for compatible, binding in sorted(bindings.items()):
        lines.append(f"| @ref {slug(compatible)} \"{compatible}\" | `{binding['driver']}` "
                     f"| {cell(binding.get('description', ''))} |")
    for compatible, binding in sorted(bindings.items()):
        directory = binding["directory"].relative_to(root).as_posix()
        page = DRIVER_PAGES.get(binding["directory"].name)
        lines += ["", f"@section {slug(compatible)} {compatible}", "",
                  cell(binding.get("description", "")), ""]
        lines += ["| | |", "| --- | --- |",
                  f"| Driver prefix | `{binding['driver']}` |",
                  f"| Sources | {', '.join(f'`{directory}/{s}`' for s in binding.get('sources', []))} |",
                  f"| Binding | `{directory}/{compatible}.yaml` |"]
        if page:
            lines.append(f"| Guide | @ref {page} |")
        flags = [key for key in CAPABILITIES if binding.get(key)]
        lines.append("| Provides | " + ("<br>".join(CAPABILITIES[key] for key in flags) or "—")
                     + " |")
        properties = binding.get("properties", {})
        if properties:
            lines += ["", "| Property | Type | Required | Default | Constraints | C field | Description |",
                      "| --- | --- | --- | --- | --- | --- | --- |"]
            for name, spec in properties.items():
                lines.append(
                    f"| `{name}` | `{spec['type']}` | {'yes' if spec.get('required') else 'no'} "
                    f"| {default(spec)} | {cell(constraints(spec))} "
                    f"| {('`' + spec['field'] + '`') if 'field' in spec else '—'} "
                    f"| {cell(spec.get('description', ''))} |")
        uses = used.get(compatible, [])
        lines += ["", "Enabled by: " + ("; ".join(
            f"`{label}` ({', '.join(f'`{n}`' for n in names)})" for label, names in uses)
            if uses else "no board yet.")]
    lines += ["*/", ""]
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--output", required=True, help="Doxygen page to write")
    args = parser.parse_args()
    root = Path(__file__).resolve().parents[1]
    try:
        bindings = dt.load_bindings(root / "src/drivers")
        used = usage(root / "src/board", root / "src/soc", root / "src/arch")
    except dt.DescriptionError as error:
        print(f"bindings_doc: {error}", file=sys.stderr)
        return 1
    page = render(bindings, used, root)
    # The page is one C comment: "*/" in a binding's text would end it early.
    if "*/" in page[page.index("\n"):page.rindex("*/")]:
        print("bindings_doc: a binding's text contains '*/'", file=sys.stderr)
        return 1
    output = Path(args.output)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(page, encoding="utf-8")
    return 0


if __name__ == "__main__":
    sys.exit(main())
