#!/usr/bin/env python3

import argparse
import os
import sys

import kconfiglib


def cmake_escape_string(value: str) -> str:
    value = value.replace("\\", "\\\\")
    value = value.replace('"', '\\"')
    return value


def write_cmake_config(kconf: kconfiglib.Kconfig, path: str) -> None:
    os.makedirs(os.path.dirname(path), exist_ok=True)

    with open(path, "w", encoding="utf-8") as f:
        f.write("# Generated by kconfig_generate.py\n")
        f.write("# Do not edit manually.\n\n")

        for sym in sorted(kconf.unique_defined_syms, key=lambda s: s.name or ""):
            if not sym.name:
                continue

            name = f"CONFIG_{sym.name}"

            if sym.type in (kconfiglib.BOOL, kconfiglib.TRISTATE):
                if sym.str_value == "y":
                    f.write(f"set({name} ON)\n")
                else:
                    f.write(f"set({name} OFF)\n")

            elif sym.type in (kconfiglib.INT, kconfiglib.HEX):
                value = sym.str_value
                if value:
                    f.write(f"set({name} {value})\n")

            elif sym.type == kconfiglib.STRING:
                value = cmake_escape_string(sym.str_value)
                f.write(f'set({name} "{value}")\n')


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--kconfig", required=True)
    parser.add_argument("--defconfig", required=True)
    parser.add_argument("--config-out", required=True)
    parser.add_argument("--header-out", required=True)
    parser.add_argument("--cmake-out", required=True)
    args = parser.parse_args()

    os.environ["srctree"] = os.getcwd()

    kconf = kconfiglib.Kconfig(args.kconfig)

    if os.path.exists(args.defconfig):
        kconf.load_config(args.defconfig)
    else:
        print(f"error: defconfig not found: {args.defconfig}", file=sys.stderr)
        return 1

    os.makedirs(os.path.dirname(args.config_out), exist_ok=True)
    os.makedirs(os.path.dirname(args.header_out), exist_ok=True)
    os.makedirs(os.path.dirname(args.cmake_out), exist_ok=True)

    kconf.write_config(args.config_out)
    kconf.write_autoconf(args.header_out)
    write_cmake_config(kconf, args.cmake_out)

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
