if(NOT DEFINED HOMECORE_BOARD_MEMORY)
    message(FATAL_ERROR "HOMECORE_BOARD_MEMORY is not defined by board")
endif()

if(NOT DEFINED HOMECORE_BOARD_LINKER_SCRIPT)
    message(FATAL_ERROR "HOMECORE_BOARD_LINKER_SCRIPT is not defined by board")
endif()

if(NOT DEFINED HOMECORE_SOC_LINKER_SCRIPT)
    message(FATAL_ERROR "HOMECORE_SOC_LINKER_SCRIPT is not defined by soc")
endif()

if(NOT DEFINED HOMECORE_ARCH_LINKER_SCRIPT)
    message(FATAL_ERROR "HOMECORE_ARCH_LINKER_SCRIPT is not defined by arch")
endif()

set(HOMECORE_GENERATED_DIR ${CMAKE_BINARY_DIR}/generated)
file(MAKE_DIRECTORY ${HOMECORE_GENERATED_DIR})

set(HOMECORE_GENERATED_LINKER_SCRIPT ${HOMECORE_GENERATED_DIR}/linker.ld)

configure_file(
    ${HOMECORE_ROOT}/cmake/linker.ld.in
    ${HOMECORE_GENERATED_LINKER_SCRIPT}
    @ONLY
)

target_link_options(homecore PRIVATE
    ${HOMECORE_ARCH_LINK_OPTIONS}
    -T${HOMECORE_GENERATED_LINKER_SCRIPT}
)

set_property(TARGET homecore APPEND PROPERTY LINK_DEPENDS
    ${HOMECORE_GENERATED_LINKER_SCRIPT}
    ${HOMECORE_ARCH_LINKER_SCRIPT}
    ${HOMECORE_SOC_LINKER_SCRIPT}
)