// SPDX-License-Identifier: MIT
#include "homecore/arch/arch.h"

/* STM32F407 peripheral vectors 0-81, generated from the CMSIS IRQn_Type enum.
 * Every implemented interrupt enters arch_irq_entry(), which dispatches to the
 * owning device through the device description. Zero entries are reserved. */
__attribute__((used, section(".isr_vector.soc"), aligned(4))) void (*const soc_vectors[])(void) = {
    arch_irq_entry, /*  0 WWDG */
    arch_irq_entry, /*  1 PVD */
    arch_irq_entry, /*  2 TAMP_STAMP */
    arch_irq_entry, /*  3 RTC_WKUP */
    arch_irq_entry, /*  4 FLASH */
    arch_irq_entry, /*  5 RCC */
    arch_irq_entry, /*  6 EXTI0 */
    arch_irq_entry, /*  7 EXTI1 */
    arch_irq_entry, /*  8 EXTI2 */
    arch_irq_entry, /*  9 EXTI3 */
    arch_irq_entry, /* 10 EXTI4 */
    arch_irq_entry, /* 11 DMA1_Stream0 */
    arch_irq_entry, /* 12 DMA1_Stream1 */
    arch_irq_entry, /* 13 DMA1_Stream2 */
    arch_irq_entry, /* 14 DMA1_Stream3 */
    arch_irq_entry, /* 15 DMA1_Stream4 */
    arch_irq_entry, /* 16 DMA1_Stream5 */
    arch_irq_entry, /* 17 DMA1_Stream6 */
    arch_irq_entry, /* 18 ADC */
    arch_irq_entry, /* 19 CAN1_TX */
    arch_irq_entry, /* 20 CAN1_RX0 */
    arch_irq_entry, /* 21 CAN1_RX1 */
    arch_irq_entry, /* 22 CAN1_SCE */
    arch_irq_entry, /* 23 EXTI9_5 */
    arch_irq_entry, /* 24 TIM1_BRK_TIM9 */
    arch_irq_entry, /* 25 TIM1_UP_TIM10 */
    arch_irq_entry, /* 26 TIM1_TRG_COM_TIM11 */
    arch_irq_entry, /* 27 TIM1_CC */
    arch_irq_entry, /* 28 TIM2 */
    arch_irq_entry, /* 29 TIM3 */
    arch_irq_entry, /* 30 TIM4 */
    arch_irq_entry, /* 31 I2C1_EV */
    arch_irq_entry, /* 32 I2C1_ER */
    arch_irq_entry, /* 33 I2C2_EV */
    arch_irq_entry, /* 34 I2C2_ER */
    arch_irq_entry, /* 35 SPI1 */
    arch_irq_entry, /* 36 SPI2 */
    arch_irq_entry, /* 37 USART1 */
    arch_irq_entry, /* 38 USART2 */
    arch_irq_entry, /* 39 USART3 */
    arch_irq_entry, /* 40 EXTI15_10 */
    arch_irq_entry, /* 41 RTC_Alarm */
    arch_irq_entry, /* 42 OTG_FS_WKUP */
    arch_irq_entry, /* 43 TIM8_BRK_TIM12 */
    arch_irq_entry, /* 44 TIM8_UP_TIM13 */
    arch_irq_entry, /* 45 TIM8_TRG_COM_TIM14 */
    arch_irq_entry, /* 46 TIM8_CC */
    arch_irq_entry, /* 47 DMA1_Stream7 */
    arch_irq_entry, /* 48 FSMC */
    arch_irq_entry, /* 49 SDIO */
    arch_irq_entry, /* 50 TIM5 */
    arch_irq_entry, /* 51 SPI3 */
    arch_irq_entry, /* 52 UART4 */
    arch_irq_entry, /* 53 UART5 */
    arch_irq_entry, /* 54 TIM6_DAC */
    arch_irq_entry, /* 55 TIM7 */
    arch_irq_entry, /* 56 DMA2_Stream0 */
    arch_irq_entry, /* 57 DMA2_Stream1 */
    arch_irq_entry, /* 58 DMA2_Stream2 */
    arch_irq_entry, /* 59 DMA2_Stream3 */
    arch_irq_entry, /* 60 DMA2_Stream4 */
    arch_irq_entry, /* 61 ETH */
    arch_irq_entry, /* 62 ETH_WKUP */
    arch_irq_entry, /* 63 CAN2_TX */
    arch_irq_entry, /* 64 CAN2_RX0 */
    arch_irq_entry, /* 65 CAN2_RX1 */
    arch_irq_entry, /* 66 CAN2_SCE */
    arch_irq_entry, /* 67 OTG_FS */
    arch_irq_entry, /* 68 DMA2_Stream5 */
    arch_irq_entry, /* 69 DMA2_Stream6 */
    arch_irq_entry, /* 70 DMA2_Stream7 */
    arch_irq_entry, /* 71 USART6 */
    arch_irq_entry, /* 72 I2C3_EV */
    arch_irq_entry, /* 73 I2C3_ER */
    arch_irq_entry, /* 74 OTG_HS_EP1_OUT */
    arch_irq_entry, /* 75 OTG_HS_EP1_IN */
    arch_irq_entry, /* 76 OTG_HS_WKUP */
    arch_irq_entry, /* 77 OTG_HS */
    arch_irq_entry, /* 78 DCMI */
    0,              /* 79 reserved */
    arch_irq_entry, /* 80 RNG */
    arch_irq_entry, /* 81 FPU */
};
